version: '3.9'

services:

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - rag-net

  generator:
    build:
      context: ./generator
      dockerfile: src/Dockerfile
    environment:
      - REDIS_HOST=redis
      - MODEL_PATH=/app/models/mistral.gguf
      - N_CTX=2048
      - N_THREADS=4
      - N_GPU_LAYERS=0
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./generator/models:/app/models:ro
    depends_on:
      - redis
    networks:
      - rag-net

  retriever:
    build:
      context: ./retriever
      dockerfile: src/Dockerfile
    environment:
      - REDIS_HOST=redis
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - redis
    networks:
      - rag-net

  gateway:
    build:
      context: ./gateway
      dockerfile: src/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - redis
      - retriever
    networks:
      - rag-net

networks:
  rag-net:
    driver: bridge
